language: python
python:
        - 3.6
env:
        - TOXENV=py34
        - TOXENV=py35
        - TOXENV=py36
        - TOXENV=codecov
        - TOXENV=flake8
        - TOXENV=pylint
        - TOXENV=mypy
install:
        - travis_retry pip install tox
script: tox -e $TOXENV
